### ISSUE TITLE
ix-select not working when applying data using Angular's ReactiveForms

### ISSUE THREAD

**Issue by marcossiemens** [siemens/ix#1076]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

When I apply data inside a formGroup using Angular's ReactiveForms like so: `this.form.get('select').setValue(this.data.select.selectId);`, the ix-select doesn't show the item selected.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
Typescript:
this.form.get('select').setValue(this.data.select.selectId);

HTML:
<ix-select id="select" formControlName="select"> <ix-select-item *ngFor="let select of selects" [label]="select.selectName" [value]="select.selectId"> </ix-select-item></ix-select>
```

**Comment by matthiashader** [comment]
Internal ref [IX-912]

**Comment by jul-lam** [comment]
There is no need to wait for the next patch release, since using a string value for the `value` property of `ix-select-item` fixes the issue. In your case changing the `selectId` from `number` to `string` does the job.

**Note**: In future releases the `value` property will be of type `string` instead of `any`.

**Comment by marcossiemens** [comment]
@jul-lam it works as you said. Thanks!
