### ISSUE TITLE
ix-button add alarm color options

### ISSUE THREAD

**Issue by KaiSoellch** [siemens/ix#1117]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### Suggestion / feature request

it would be a good idea to have a red button for e.g. actions to delete data

![image](https://github.com/siemens/ix/assets/1941783/3652f029-a672-4c7c-923d-52742d5830c0)

I have created a pen that will realise this, apart from it being an angular demo app, the changes only affect css
https://stackblitz.com/edit/zhex5c?file=src%2Fapp%2Fbuttons.ts

but for correct documentation and possibilities, the alert variant should be included. Also in the base component like here
https://github.com/siemens/ix/blob/main/packages/core/src/components/button/button.tsx#L13
and other references

**Comment by KaiSoellch** [comment]
if desired, i can also integrate this into the ix-button component and create a pull request

**Comment by danielleroux** [comment]
@KaiSoellch The requirement is already tracked in our internal backlog to provide more button variants [IX-364]

@silviowolf @kathrinschalber @linstedt Maybe you can give more insights here?

**Comment by KaiSoellch** [comment]
Here is some backstory on my needs within my application, which I am currently rewriting completely to only use ix components
![image](https://github.com/siemens/ix/assets/1941783/6a05a4ae-9b60-45ba-85b0-25b15c564bec)

**Comment by kathrinschalber** [comment]
Hi @KaiSoellch and thanks for the example - as @danielleroux already pointed out, the red button you shared for user delete is already on our backlog for dangerous actions, including a filled, outline and ghost style similar to the primary button.

We also discussed the behavior for the warning button. Instead of introducing another button type, we suggest using the grey secondary button or the outline or ghost version of the danger button, depending on the use case, to ensure clarity for our users. Would this proposed solution align with your requirements?

**Comment by KaiSoellch** [comment]
hi @kathrinschalber thanks for your insights. these buttons are only for admins so i change them if your version of danger action buttons are available. in the meantime i will leave them as is.
