### ISSUE TITLE
[Idea] Storybook for siemens-ix

### ISSUE THREAD

**Issue by ridvandmrc** [siemens/ix#1130]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### Suggestion / feature request

Almost all of the design system has storybook, because  it provides documentation and usage of the component. 
also sometimes the document is not enough to understand the usage of the component so that I suggest you to have storybook.
If you have I believe that you will have less question from community.
let me list some benefit of it:
* It is fast and efficient for development
* Ease access to component
* Usage of the component's property and events
* Usage of the addon like playground.

as examples:
* https://react.carbondesignsystem.com/
* https://baklava.design/?path=/docs/documentation-welcome--documentation
* https://jellods-devops.rochedc.accentureanalytics.com/?path=/story/components-chip--default

Is it possible to have this kind of a feature? or do we already have?

**Comment by matthiashader** [comment]
Thanks for reaching out to us and sharing some feedback! At the moment, we are not planning / supporting a feature like storybooks, as all our documentation is on the iX homepage. Could you kindly provide further insights which specific aspects you believe we could implement in order to improve our documentation?
