### ISSUE TITLE
Category Filter | Category Filter must have provision to show category based on some condition in dropdown menu.

### ISSUE THREAD

**Issue by Jayesh26** [siemens/ix#1265]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Suggestion / feature request

In "[categories]" we have added list of categories but in real time we have use case to show/hide some category based on previous category and its value.

categories = [ Cat1:{ },  Cat2:{ },  Cat3:{ },  Cat4:{ }   ]

So eg. **Cat1**  has selected value as **Cat1-Val**  In this case we do not want to show Cat2 and Cat3 in the dropdown list once user click on selecting new category. 

![image](https://github.com/siemens/ix/assets/3745459/3b0564d2-0412-487e-a754-311997173bc6)

**Comment by nuke-ellington** [comment]
Hello @Jayesh26,

You should be able to set the `categories` property during runtime to adapt it to the current selection. We will not be able to provide custom logic like the one you described since this is too specific. Please feel free to reopen the issue in case the above solution does not work from a technical standpoint.
