### ISSUE TITLE
Category Filter | Dedicated callback method for executing search query / API call 

### ISSUE THREAD

**Issue by Jayesh26** [siemens/ix#1266]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Suggestion / feature request

As there is no method for executing search after some specific event like **"Enter"** button got clicked. 
Or some UI option in dropdown to confirm all required categories has been added now can proceed for search.

There are below callback provided but they also get trigger multiple times when specific operation performed eg in case of categoryChanged event it will call multiple time when we add new category and select value for it. 

categoryChanged:  category gets selected in the dropdown
filterChanged:  filter state changes
inputChanged:  text input changes

So we do not have that event as when we should trigger the search call execution or do we need to add some Search icon beside Category filter.

**Comment by nuke-ellington** [comment]
Hello @Jayesh26, the component is a filter as the name implies. Therefor it does not have a dedicated "send" button. The data should only get filtered every time the filter state changes (`filterChanged`). This should reduce your backend calls to a minimum.
I will close this since I don't see an issue currently, but feel free to reopen in case you have a strong use case that cannot be implemented currently.
