### ISSUE TITLE
Status of progress bar component

### ISSUE THREAD

**Issue by muratayik** [siemens/ix#1309]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Suggestion / feature request

Hi, we are planning to use progress bar in our application. I can see that there is already a [pull request](https://github.com/siemens/ix/pull/1248) waiting. Is there an estimated time for progress bar to be released?

**Comment by danielleroux** [comment]
@muratayik We are discussed this in code team to take over the pullrequest because the original author stopped working on the pull request. We dont has a estimate date.

I will close this issue here. If you have any other questions please use our community forums:
- https://community.siemens.com/c/ix/30
or
- https://engage.cloud.microsoft/main/groups/eyJfdHlwZSI6Ikdyb3VwIiwiaWQiOiI1ODIzNzc5NjM1MiJ9/all
