### ISSUE TITLE
IxSelect with form validation is broken 

### ISSUE THREAD

**Issue by tobiask84** [siemens/ix#1573]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

IxSelect with is-invalid is buggy. This has already been mentioned here:
https://github.com/siemens/ix/issues/1389

The ticket was moved to closed but I cant find any changes in the docs of form validation? How is this used? It still looks like in the attached screenshot to me:
![image](https://github.com/user-attachments/assets/92db106e-66af-421f-b434-c697749e9d27)

### What type of frontend framework are you seeing the problem on?

React

### Which version of iX do you use?

v.2.5.0 

### Code to produce this issue.

```shell
This is version 2.5 of ix. Here is the code in react:

        <IxSelect
          className="is-invalid"
          ...

I cannot see selects being mentioned here:
https://ix.siemens.io/docs/controls/validation
```

**Comment by danielleroux** [comment]
The issue https://github.com/siemens/ix/issues/1389 was closed because its merged on main already (PR: https://github.com/siemens/ix/pull/1318). In the PR you will find another linked PR which contains the information about which version the library will take for the release:
![image](https://github.com/user-attachments/assets/2b8b91b7-57c6-482b-b73f-e1fa6707a5e5)
e.g #1480 
The issue will be part of the next release
