### ISSUE TITLE
Select component - different behavior after update to 2.6.X

### ISSUE THREAD

**Issue by ugurbayraktarr** [siemens/ix#1626]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

When the user clears the value of the Select component, the value of onValueChange is an empty array. In previous versions it was null. 
Is it a bug, or expected behavior?

### What type of frontend framework are you seeing the problem on?

React

### Which version of iX do you use?

v2.6.1

### Code to produce this issue.

```shell
Steps to reproduce:
- Select a value
- Click the clear icon

ix 2.5.0: https://stackblitz.com/edit/vwaqrkw4-4txap4vx?file=package.json
ix 2.6.0: https://stackblitz.com/edit/vwaqrkw4-y4cujgze?file=package.json
```

**Comment by nuke-ellington** [comment]
Hello @ugurbayraktarr,

thank you for reaching out.

The return value of `null` was actually a bug since the data type of the `value` property is `string | string[]` which cannot be `null` and defaults to `[]`.

See also `ix-select` [API table](https://ix.siemens.io/docs/controls/select?current-tab=development#api-ix-select).
