### ISSUE TITLE
Resizable Map Navigation sidebar

### ISSUE THREAD

**Issue by tomas-reznak** [siemens/ix#298]
### Suggestion / feature request

I think it would be nice to have the sidebar resizable (e.i. to be able to drag the line separating the sidebar and the main content to change the sidebar's width).

This would allow the user to increase the sidebar width in case they need to view text that would otherwise be too long to fully render and to adjust it to their specific needs and likes.

![image](https://user-images.githubusercontent.com/99844553/212335294-869d836b-d0f9-436e-a059-f47cf99d4fa0.png)

**Comment by silviowolf** [comment]
Hi @tomas-reznak,
thanks for you suggestion. We discussed the pros and cons internally.
The Map Navigation is built for a very specific usecase where a kind of map/canvas is main content and the sidebar provides additional info or content to control the map/canvas (similar to google maps). An user controlled width would cause different other problems that need to be catched and handled and the component is due to its specialization rarely used in projects. So we decided to not enhance the component.
