### ISSUE TITLE
Xcelerator Theme for Ix?

### ISSUE THREAD

**Issue by sn0wcat** [siemens/ix#350]
### Suggestion / feature request

I love it that we have a wide range of themes already for Siemens IX. Could we please also have a "Xcelerator Theme" for iX - Siemens Dark doesnt quite cut it because of difference in colors. 

Color palette of marketplace

![image](https://user-images.githubusercontent.com/1426617/216561880-e546115e-1db9-46eb-a853-e8d3b9d8f9b1.png)

Colors of Siemens Dark

![image](https://user-images.githubusercontent.com/1426617/216562165-fdce7410-fcfc-4ad1-ae3e-63486523b70f.png)

**Comment by sn0wcat** [comment]
Having a theme like this would make it easier to integrate iX into in the documentation portals , marketplace etc.

**Comment by silviowolf** [comment]
Hi @sn0wcat, thanks for your suggestion.
I am not quite sure if I understand your intention completely. The range of iX themes is actually not that wide. There are only Brand light & dark, mandatory for Siemens apps built with iX and there are Classic light & dark that can be used for non-Siemens apps as the iX is OpenSource. There will not be a separate Xcelerator theme in future since also the Xcelerator initiative follows the general Brand Experience.
The iX Brand themes stick as close as technical possible to the Brand guidelines for Desktop applications. If the mentionend portals and marketplaces use different colors e.g. for tabs, search, buttons or other components I would rather see a to-do on their side to align with the Brand guidelines. But you should also know, Brand's guidelines for "Online" and "Desktop" are different in detail to take their different requirements and usecases into account. Additionally, there are also technical limitations that some portal or documentation solutions have and so it will most likely not be easy to apply iX afterwards to a fully developed solution.

**Comment by sn0wcat** [comment]
If both of these pages are folowing the guidelines, then my guess is that this explains the differences between (e.g.):

primary button color - marketplace.siemens.com: `#009999' - font color 'white' (my guess online guideline)
primary button color - siemens dark theme iX: '#00cccc' - font color 'black' (my guess brand app guideline)

The header and sidebar colors are also different etc. The differences might be subtle but deffinitely visible. I am asking the question because we are currently gathering informations about the things which we would like to integrate into / link from a future developer portal and iX documentation is one of them.
