### ISSUE TITLE
Tooltip is not working

### ISSUE THREAD

**Issue by lisafixl** [siemens/ix#483]
### What happened?

Hi,

I am trying to use the ix-tooltip for a text, which is shortened and by hover above it  the overflow of the text should be shown within the tooltip. I tried some things like:

`<div class="deviceCard__headline text-l-title" id="deviceName" data-tooltip="myTooltip">
                  {this.data.name}
                </div>
                <ix-tooltip for="[data-tooltip='myTooltip']">{this.data.name}</ix-tooltip>` 

I also tried to use the id="deviceName" to refer to the tooltip, but nothing works. Therefore I have a question. Is it possible to use the tooltip for text?

Further I tried the example from the ix docs:

`<div>
                  <ix-button data-tooltip="myTooltip">Hover me</ix-button>
                  <ix-tooltip for="[data-tooltip='myTooltip']">Some example content</ix-tooltip>
                </div>`

which also does not work. By inspecting the code I saw that the tooltip is there within the html, but nothing is shown when I hover above the button like in the example.

**Comment by danielleroux** [comment]
@lisafixl

Which version of ix do you use?
Do you use any Frameworkwork like React, Angular or Vue

**Comment by danielleroux** [comment]
The code that you mentioned in the beginning is no angular template language.

**Comment by katjaKoppensteiner** [comment]
Hi @danielleroux,

@lisafixl  is my colleague and I also invested some time into this topic, i figured out that the "for" attribute just gets ignored by the JSX transpiler.

So we are using StencilJs to build a webcomponent by reusing your iX webcomponents - we need a project specific webcomponent.

I just have inserted this variant, as you can see with several variants for inserting the "for" attribute
`
<ix-button data-tooltip="myTooltip">Hover me</ix-button>
 <ix-tooltip ref={el => el.for = '[data-tooltip=\'myTooltip\']'} htmlFor="[data-tooltip='myTooltip']" for="[data-tooltip='myTooltip']">
                Some example content
 </ix-tooltip>
`

What get's rendered in the end is:
![image](https://user-images.githubusercontent.com/109066516/233101654-6bf009e8-401c-4446-8228-aca87ee91a3d.png)

After some research I figured out that Jsx ignores the "for" attribute anyway and it should be replaced with "htmlFor"
https://stackoverflow.com/questions/29161330/react-js-ignores-labels-for-attribute
https://timmousk.com/blog/react-label-for/#:~:text=We%20use%20the%20%22for%22%20attribute,of%20the%20%22for%22%20attribute.

We can connect within a meeting if you want, because we are both working at the same company.

But my question is, is your implementation really working with a React setup or is there a bug?

We tested the same code with Angular and there it is working.

**Comment by danielleroux** [comment]
Okay i analyzed this on the previous information from @lisafixl which was angular as target platform. If you try it with stencil then for sure we have to check the jsx transpiler limitations as well.

**Comment by katjaKoppensteiner** [comment]
@danielleroux we are sorry for the miscommunication, this was our mistake.
Do you need additional information from our side?

**Comment by danielleroux** [comment]
I cannot reproduce your issue.

My example:

```tsx
import { defineCustomElements } from '@siemens/ix/loader';
import { Component, Prop, h } from '@stencil/core';
import { format } from '../../utils/utils';

(async () => {
  await defineCustomElements();
})();

@Component({
  tag: 'myx-component',
  styleUrl: 'my-component.css',
  scoped: true,
})
export class MyComponent {
  /**
   * The first name
   */
  @Prop() first: string;

  /**
   * The middle name
   */
  @Prop() middle: string;

  /**
   * The last name
   */
  @Prop() last: string;

  private getText(): string {
    return format(this.first, this.middle, this.last);
  }

  render() {
    return (
      <div>
        Hello, World! I'm <ix-button id="test">{this.getText()}</ix-button>
        <ix-tooltip for="#test">Test</ix-tooltip>
      </div>
    );
  }
}

```

**Comment by katjaKoppensteiner** [comment]
Hi @danielleroux 

in your documentation it is written that a "data-tooltip" attribute has to be used to make this working,in your code above you have used an id.

![image](https://github.com/siemens/ix/assets/109066516/c31c8f9b-d641-4593-9258-b8679d9d9be8)

with your proposal it is also working on my system...
![image](https://github.com/siemens/ix/assets/109066516/e680386a-8e79-40b2-9644-9f3071c323c0)

Please correct your documentation and have a more detailled look before a release if it is complete and detailled.

**Comment by danielleroux** [comment]
The documentation is correct
![image](https://github.com/siemens/ix/assets/2144313/dc7a6a21-19f0-4327-a3d7-382d97ffdf67)

**Comment by katjaKoppensteiner** [comment]
in our case it is not working with data-tooltip, we have to use id because data-tooltip get's removed by jsx compiler.

![image](https://github.com/siemens/ix/assets/109066516/63ca1743-b461-4c09-aa58-b0ec232cf616)

in your documentation it is only mentioned that for="something" but in combination with data-tooltip, not with id.
for us as developers it would be really helpful to have it in a more detailled way.

**Comment by danielleroux** [comment]
You dont have to use `id` you can use any css selector you want e.g.

```tsx
<>
<ix-button class="any-class">Some text</ix-button>
<ix-tooltip for=".any-class">Test</ix-tooltip>
</>
```

**Comment by katjaKoppensteiner** [comment]
This was not clear to us only when reading the documentation, thank's for your advise.
Maybe you can add such examples or more explaining text to the documentation, that would be great.
