### ISSUE TITLE
Usage of elevation levels

### ISSUE THREAD

**Issue by danielbruns93** [siemens/ix#630]
### Suggestion / feature request

For almost all of our projects it is unclear "if at all, when or which element" has to be placed on an elevation level that is described by Brandville. 
We would appreciate if you could ad a common usage description in the "Foundation" or "Guideline" section of iX that answers:
- "When you have component X and Y, then you need to put the together on elevation Z"
- Which components should not be placed on an elevation level (don'ts)
- Best practises (Do's)
Many thank

**Comment by danielbruns93** [comment]
Is there any update on this?

**Comment by silviowolf** [comment]
Hi @danielbruns93,
our next iX sprint is a documentation sprint with focus on guideline documentation. We will also add a chapter regarding elevation principles.
Maybe a few rules of thumb:
Elevation 0 in the brand guidelines matches to iX color "theme-color-1". This is the default background when you set up a new app. Eleveation 1 matches to "theme-color-2", Elevation 2 equals "theme-color-3" and so on. When you use a container component like the Blind (which has a color that equals elevation 2) then everything inside the Blind is automatically elevation level 2 and you don’t have to care about since we will make sure you can use every compontent, even another blind nested which will result in level 3. For sure, this will not work endlessly and this limits we will describe in the following sprint. The exceptions we currently still have (e.g. tile component) will be replaced sooner or later.

**Comment by danielbruns93** [comment]
Awesome, Thank you :) 
What triggers us is the belonging user experience of elements mostly on elevation 0 and 1. 
For example:
- a "Save" button saves all changes of the current app page. Is it then needed to group all this content including this "Save" button or can buttons and other functions (e.g. export, sort, time picker ...?....) stay in a seperate area e.g. then on elevation 0?
- when you have just a table with an function area for: search, filter, multiple icon/text buttons ... above that performs actions in relation to the table content, does the table and this area above needs to be grouped on the same elevation (and 1 or 0)?
- when you use a tab bar on a page to group certain content does all the content (and event the tab bar) needs to be grouped  on elevation 1 or which of those can stay on elevation 0?

**Comment by silviowolf** [comment]
@danielbruns93, we are cleaning up things and found your open questions. If they are still relevant, please contact me via Teams.
Thanks,
Silvio
