### ISSUE TITLE
Events can be also documented on IX

### ISSUE THREAD

**Issue by bachowsky** [siemens/ix#765]
### Suggestion / feature request

Documentation does not provide event functions such as click etc... It would be helpful, if default and event attributes were also documented.

**Comment by danielleroux** [comment]
We does not provide this because all our components are web components (which have to extends from HTMLElement) 
```typescript
    interface HTMLIxButtonElement extends Components.IxButton, HTMLStencilElement {
    }
    var HTMLIxButtonElement: {
        prototype: HTMLIxButtonElement;
        new (): HTMLIxButtonElement;
    };
```
```typescript
export interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
}
```
(https://github.com/siemens/ix/blob/main/packages/core/src/components.d.ts#L2400) in this case all component will have the properties/events and methods from HTMLElement (https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement).

e.g a click event is existing on all of our components.

**Comment by bachowsky** [comment]
Thank you for your explanation
